apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'me.ele.lancet'

android {
    compileSdkVersion versions.compileSdk

    signingConfigs {
        release {
            storeFile file("../uetool.jks")
            keyAlias 'uetool'
            keyPassword 'uetool'
            storePassword 'uetool'
        }
    }

    defaultConfig {
        applicationId "me.ele.uetool.sample"
        minSdkVersion versions.minSdk
        targetSdkVersion versions.targetSdk
        versionCode 1
        versionName "1.0"
        multiDexEnabled = true
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {

    implementation "com.facebook.fresco:fresco:${versions.fresco}"
    implementation "com.facebook.fresco:animated-gif:${versions.fresco}"

    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation "androidx.activity:activity:1.7.2"
    implementation "androidx.activity:activity-ktx:1.7.2"
    implementation "androidx.fragment:fragment:1.5.4"
    implementation 'androidx.fragment:fragment-ktx:1.5.4'
    implementation "androidx.coordinatorlayout:coordinatorlayout:1.2.0"
    implementation 'com.google.android.material:material:1.5.0'

    implementation 'android.arch.lifecycle:extensions:1.1.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:1.5.4'
    releaseImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:1.5.4'

    debugImplementation project(':uetool')
    debugImplementation project(':uetool-fresco')
    debugImplementation project(':uetool-base')
    releaseImplementation project(':uetool-no-op')
//  debugImplementation "me.ele:uetool:${versions.release}"
//  debugImplementation "me.ele:uetool-fresco:${versions.release}"
//  releaseImplementation "me.ele:uetool-no-op:${versions.release}"

    compileOnly 'me.ele:lancet-base:1.0.6'

    //磁盘文件查看工具
    implementation 'com.github.yangchong211.YCAndroidTool:MonitorFileLib:1.2.8'
//卡顿工具
    implementation 'com.github.yangchong211.YCAndroidTool:MonitorCatonLib:1.2.8'
//网络工具
    implementation 'com.github.yangchong211.YCAndroidTool:MonitorNetLib:1.2.8'
//崩溃工具
    implementation 'com.github.yangchong211.YCAndroidTool:MonitorCrashLib:1.2.8'
//anr工具
    implementation 'com.github.yangchong211.YCAndroidTool:MonitorAnrLib:1.2.8'
    implementation("androidx.multidex:multidex:2.0.1")

    configurations.all {
        resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
    }
}
